// Generated by PeakRDL-etana - A free and open-source SystemVerilog generator
//  https://github.com/daxzio/PeakRDL-etana

module regblock (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_pwrite,
        input wire s_apb_penable,
        input wire [2:0] s_apb_pprot,
        input wire [3:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr


    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;


    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[3:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    logic [0:0] decoded_reg_strb_status;
    logic [0:0] decoded_reg_strb_busy;
    logic [0:0] decoded_reg_strb_config;
    logic [0:0] decoded_reg_strb_interrupt;
    logic decoded_req;
    logic decoded_req_is_wr;
    /* verilator lint_off UNUSEDSIGNAL */
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;
    /* verilator lint_on UNUSEDSIGNAL */

    always @(*) begin
        /* verilator lint_off UNUSEDSIGNAL */
        integer next_cpuif_addr;
        /* verilator lint_on UNUSEDSIGNAL */
        decoded_reg_strb_status = cpuif_req_masked & (cpuif_addr == 4'h0);
        decoded_reg_strb_busy = cpuif_req_masked & (cpuif_addr == 4'h4);
        decoded_reg_strb_config = cpuif_req_masked & (cpuif_addr == 4'h8);
        decoded_reg_strb_interrupt = cpuif_req_masked & (cpuif_addr == 4'hc);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;


    //--------------------------------------------------------------------------
    // Field storage declarations
    //--------------------------------------------------------------------------

    // Field: regblock.STATUS.STATUS
    logic [7:0] field_storage_status_value;
    logic [7:0] field_combo_status_next;
    logic field_combo_status_load_next;
    // Field: regblock.BUSY.BUSY
    logic [7:0] field_storage_busy_value;
    logic [7:0] field_combo_busy_next;
    logic field_combo_busy_load_next;
    // Field: regblock.CONFIG.CONFIG
    logic [7:0] field_storage_config_value;
    logic [7:0] field_combo_config_next;
    logic field_combo_config_load_next;
    // Field: regblock.INTERRUPT.INTERRUPT
    logic [7:0] field_storage_interrupt_value;
    logic [7:0] field_combo_interrupt_next;
    logic field_combo_interrupt_load_next;
    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    // always_comb begin
    always @(*) begin
        logic [7:0] next_c;
        logic load_next_c;
        next_c = field_storage_status_value;
        load_next_c = '0;
        if(decoded_reg_strb_status && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_status_value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo_status_next = next_c;
        field_combo_status_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_status_value <= 8'h12;
        end else if(field_combo_status_load_next) begin
            field_storage_status_value <= field_combo_status_next;
        end
    end
    // always_comb begin
    always @(*) begin
        logic [7:0] next_c;
        logic load_next_c;
        next_c = field_storage_busy_value;
        load_next_c = '0;
        if(decoded_reg_strb_busy && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_busy_value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo_busy_next = next_c;
        field_combo_busy_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_busy_value <= 8'h34;
        end else if(field_combo_busy_load_next) begin
            field_storage_busy_value <= field_combo_busy_next;
        end
    end
    // always_comb begin
    always @(*) begin
        logic [7:0] next_c;
        logic load_next_c;
        next_c = field_storage_config_value;
        load_next_c = '0;
        if(decoded_reg_strb_config && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_config_value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo_config_next = next_c;
        field_combo_config_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_config_value <= 8'h56;
        end else if(field_combo_config_load_next) begin
            field_storage_config_value <= field_combo_config_next;
        end
    end
    // always_comb begin
    always @(*) begin
        logic [7:0] next_c;
        logic load_next_c;
        next_c = field_storage_interrupt_value;
        load_next_c = '0;
        if(decoded_reg_strb_interrupt && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_interrupt_value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo_interrupt_next = next_c;
        field_combo_interrupt_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_interrupt_value <= 8'h78;
        end else if(field_combo_interrupt_load_next) begin
            field_storage_interrupt_value <= field_combo_interrupt_next;
        end
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

//--------------------------------------------------------------------------
// Readback
//--------------------------------------------------------------------------
    logic readback_external_rd_ack;
    assign readback_external_rd_ack = 0;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[4];
    assign readback_array[0][7:0] = (decoded_reg_strb_status && !decoded_req_is_wr) ? field_storage_status_value : '0;
    assign readback_array[0][31:8] = '0;
    assign readback_array[1][7:0] = (decoded_reg_strb_busy && !decoded_req_is_wr) ? field_storage_busy_value : '0;
    assign readback_array[1][31:8] = '0;
    assign readback_array[2][7:0] = (decoded_reg_strb_config && !decoded_req_is_wr) ? field_storage_config_value : '0;
    assign readback_array[2][31:8] = '0;
    assign readback_array[3][7:0] = (decoded_reg_strb_interrupt && !decoded_req_is_wr) ? field_storage_interrupt_value : '0;
    assign readback_array[3][31:8] = '0;

    // Reduce the array
    // always_comb begin
    always @(*) begin
        logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<4; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
